version: "3"
services:
  app:
    container_name: "thermobug"
    restart: always
    build: ../
    ports:
      - "8111:8111"
    links:
      - mongo
    environment:
      - THERMOBUG_KEYS=server,backup,cluster1,cluster2,cluster3,cluster4
      - THERMOBUG_BIND_ADDR=0.0.0.0:8111
      - THERMOBUG_MAX_RECORDS=7200
      - THERMOBUG_WORKER_THREADS=1
      - THERMOBUG_DB_ADDR=mongodb://mongo:27017
      - THERMOBUG_DB_NAME=thermobug
      - THERMOBUG_PERSIST_INTERVAL=3600
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    expose:
      - "27017"
    logging:
      driver: "none"
