version: "3"
services:
  thermobug-app:
    container_name: thermobug-app
    restart: always
    image: eleanorem/thermobug
    ports:
      - "8111:8111"
    networks:
      - thermobug-net
    environment:
      - THERMOBUG_KEYS=ouranos,atlas,bellerophon,cerberus,daedalus,eurydice
      - THERMOBUG_BIND_ADDR=0.0.0.0:8111
      - THERMOBUG_MAX_RECORDS=7200
      - THERMOBUG_WORKER_THREADS=1
      - THERMOBUG_DB_ADDR=mongodb://thermobug-mongo:27017
      - THERMOBUG_DB_NAME=thermobug
      - THERMOBUG_PERSIST_INTERVAL=3600
  thermobug-mongo:
    container_name: thermobug-mongo
    restart: always
    image: mongo
    volumes:
      - data:/data/db
    expose:
      - "27017"
    logging:
      driver: "none"
    networks:
      - thermobug-net

networks:
  thermobug-net:
    driver: bridge

volumes:
  data:
