version: "3"
services:
  app:
    container_name: "thermobug"
    restart: always
    build: ../
    ports:
      - "8111:8111"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:data/db
    expose:
      - "27017"
